### ISSUE TITLE
-present idea to teacher

### ISSUE THREAD

**Issue by CoderCatA5** [MadKauSing/GuessFlat#1]
-present and explore frameworks and tools for this project

**Comment by CoderCatA5** [comment]
@AyushmaanKaushik @BhaviniMadhuranath  i think we will be using github projects to track progress(trying to avoid something like linear) -- reply to this comment just as a test.

**Comment by AyushmaanKaushik** [comment]
Okay

**Comment by BhaviniMadhuranath** [comment]
okay
