### ISSUE TITLE
Add helper to take screenshot and resize and reshape it

### ISSUE THREAD

**Issue by CoderCatA5** [MadKauSing/GuessFlat#20]
- use opencv
- convert to faster color codes

**Comment by ramselvaraj** [comment]
hey, can i have this assigned to me?

**Comment by CoderCatA5** [comment]
ps submit a get_observation.py file inside the helper function

**Comment by CoderCatA5** [comment]
> hey, can i have this assigned to me?

sure @ramselvaraj
